"""Initial migration with pgvector

Revision ID: e15810b7f569
Revises: 
Create Date: 2026-07-02 21:11:44.807650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e15810b7f569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.drop_table('photo_analysis')
    op.drop_table('photo_analysis_2')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requester', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visits_pkey'))
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_table('photo_analysis_2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('norm_embedded_tensor', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_analysis_2_pkey'))
    )
    op.create_table('photo_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('norm_embedded_tensor', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=False),
    sa.Column('bounding_box', pgvector.sqlalchemy.vector.VECTOR(dim=4), autoincrement=False, nullable=False),
    sa.Column('image_labels', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_analysis_pkey'))
    )
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
